const main = async () => {
  console.log('Works');
};
main().catch(console.error);
